version: '3.9'

services:
  f1palpiteiros:
    image: ${DOCKER_REGISTRY-}f1palpiteiros
    build:
      context: f1-palpiteiros-api
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"   
    
    
  palpiteirosdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #container_name: palpiteirosdb
    env_file: ".env"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433" 
      MSSQL_OPTIONS: ${MSSQL_OPTIONS}
    volumes:
      - sqlserver_data:/var/opt/mssql
    

volumes:
  sqlserver_data:
